export const authActions = {
    SET_USER_DATA: 'AUTH/SET_USER_DATA',
    SET_LOADING: 'AUTH/SET_LOADING',
    FETCH_LOGIN: 'AUTH/FETCH_LOGIN',
    FETCH_REGISTER: 'AUTH/FETCH_REGISTER',
    FETCH_ME_PROFILE: 'AUTH/FETCH_ME_PROFILE',
    SIGN_OUT: 'AUTH/SIGN_OUT',
    SET_ERROR: 'AUTH/SET_ERROR'
}